In [2]:
import numpy as n1
import pandas as p1
from matplotlib import pyplot as plt1
import seaborn as sns

In [4]:
d1=p1.read_csv(r"F:\BosscoderExcel\shravan_test_data_13092025.csv",encoding_errors='ignore')

In [4]:
d1.sample(10)

,id,name,email,phnumber,cities,departments,prdcata,datetime,companynames
213850,7.244191e+08,John Smith,peter.ford1710@fastmail.com,+91-8158475790,Mumbai,Engineering,NaN,2001-04-21 21:23:06,Apple Inc
476550,3.199121e+09,NaN,ryan.sanchez3812@fastmail.com,NaN,Mumbai,NaN,Electronics,1971-05-04 01:23:07,Apple Inc
407222,3.432357e+09,Michael Brown,gloria.diaz3257@aol.com,+91-8748658190,Kolkata,NaN,Books,1979-03-31 17:23:07,Google
326271,2.402319e+09,Mary Rodriguez,nancy.lewis2610@msn.com,+91-1442358728,Delhi,Marketing,NaN,1988-06-24 16:23:06,Apple Inc
657581,4.170970e+09,Sarah Johnson,samuel.price4545@tempmail.org,+91-4358589703,Delhi,Sales,Clothing,1950-09-08 02:23:09,Adobe
205915,6.521636e+07,William Garcia,janet.henderson931@fastmail.com,+91-2744808411,Hyderabad,NaN,NaN,2002-03-18 12:23:06,Tesla
258620,2.988542e+08,David Wilson,bruce.robertson2068@aol.com,+91-9511735408,NaN,NaN,Electronics,1996-03-13 11:23:06,Amazon
497003,3.369451e+08,Emily Davis,emily.davis3976@gmail.com,+91-6411786805,Chennai,HR,Home & Garden,1969-01-01 20:23:08,NaN
296995,1.378983e+09,NaN,bruce.robertson2375@tempmail.org,+91-4961560018,NaN,Operations,Beauty,1991-10-27 12:23:06,Tesla
195116,2.727542e+08,Robert Taylor,albert.palmer1560@outlook.com,+91-8092355896,Pune,NaN,Automotive,2003-06-11 11:23:06,Meta

In [5]:
d2=d1.copy()

In [12]:
d2.head(20).isnull().sum()

id              0
name            0
email           0
phnumber        2
cities          0
departments     0
prdcata         3
datetime        3
companynames    3
dtype: int64

In [17]:
d2.tail(30)

,id,name,email,phnumber,cities,departments,prdcata,datetime,companynames
709470,7.376259e+09,John Smith,kathryn.russell5675@msn.com,+91-2146743308,Mumbai,Engineering,Electronics,1944-10-07 00:23:09,Apple Inc
709471,5.186796e+08,Sarah Johnson,email_empty,+91-6374762395,Delhi,Marketing,Clothing,1944-10-06 23:23:09,Microsoft
709472,3.086285e+09,Michael Brown,gloria.diaz5675@msn.com,+91-6363978078,Pune,Sales,Books,1944-10-06 22:23:09,Adobe
709473,2.365104e+08,NaN,douglas.hayes5675@msn.com,+91-6605189505,Hyderabad,Sales,Home & Garden,1944-10-06 21:23:09,empty_null_data
709474,8.583508e+08,Jennifer Martinez,email_empty,+91-5852943132,Chennai,HR,Sports,1944-10-06 20:23:09,Microsoft
709475,1.380147e+08,Lisa Anderson,peter.ford5675@rediffmail.com,+91-1114524911,Mumbai,Operations,Beauty,1944-10-06 19:23:09,empty_null_data
709476,8.394240e+07,Lisa Anderson,sara.hamilton5675@rediffmail.com,+91-1936237996,Delhi,empty_departmenst,empty_null_data,1944-10-06 18:23:09,Salesforce
709477,8.395462e+08,Robert Taylor,zachary.graham5675@rediffmail.com,+91-8683807370,Ahmedabad,Research,Toys,1944-10-06 17:23:09,Adobe
709478,2.585307e+09,William Garcia,janice.sullivan5675@rediffmail.com,empty_null_data,Jaipur,Legal,Food,1944-10-06 16:23:09,Google
709479,6.528946e+07,Mary Rodriguez,noah.wallace5675@rediffmail.com,+91-8534202702,Mumbai,Product,empty_null_data,1944-10-06 15:23:09,Oracle
709480,3.773242e+08,NaN,email_empty,empty_null_data,Pune,Engineering,Electronics,1944-10-06 14:23:09,Microsoft
709481,4.703978e+09,Sarah Johnson,christian.cole5675@inbox.com,+91-6309617788,Delhi,Marketing,Clothing,1944-10-06 13:23:09,Google
709482,6.838374e+07,Jennifer Martinez,beverly.west5675@inbox.com,+91-5768157637,Bangalore,Marketing,Books,1944-10-06 12:23:09,Google
709483,2.868603e+09,Sarah Johnson,walter.jordan5675@inbox.com,empty_null_data,Chennai,HR,Home & Garden,1944-10-06 11:23:09,Amazon
709484,NaN,NaN,email_empty,+91-3715968117,empty_cities,Product,Sports,1944-10-06 10:23:09,Meta
709485,3.325318e+08,NaN,email_empty,+91-3591613464,empty_cities,empty_departmenst,Beauty,1944-10-06 09:23:09,Tesla
709486,1.447008e+07,NaN,jean.fisher5675@hushmail.com,+91-8284047593,Jaipur,Engineering,empty_null_data,1944-10-06 08:23:09,Amazon
709487,5.221842e+07,Jennifer Martinez,email_empty,+91-1047705199,empty_cities,Finance,Toys,empty_null_data,Adobe
709488,7.808078e+07,William Garcia,judith.gibson5675@hushmail.com,+91-6801982757,empty_cities,Product,Food,1944-10-06 06:23:09,Salesforce
709489,3.689526e+08,Mary Rodriguez,arthur.mason5675@hushmail.com,+91-9614525988,Lucknow,Product,Health,1944-10-06 05:23:09,Salesforce
709490,2.589481e+08,John Smith,andrea.hunt5675@guerrillamail.com,+91-2873913032,Mumbai,Engineering,Electronics,1944-10-06 04:23:09,Apple Inc
709491,2.081961e+09,Sarah Johnson,albert.palmer5675@guerrillamail.com,+91-7340805148,empty_cities,Marketing,Clothing,1944-10-06 03:23:09,Microsoft
709492,1.270773e+09,William Garcia,rose.berry5675@guerrillamail.com,+91-6186281706,Bangalore,empty_departmenst,empty_null_data,1944-10-06 02:23:09,empty_null_data
709493,7.733720e+07,Michael Brown,wayne.rice5675@guerrillamail.com,empty_null_data,Chennai,empty_departmenst,Home & Garden,1944-10-06 01:23:09,Amazon
709494,2.045492e+08,David Wilson,theresa.chapman5675@guerrillamail.com,+91-3303590305,Kolkata,empty_departmenst,Sports,1944-10-06 00:23:09,empty_null_data
709495,3.899574e+09,Lisa Anderson,bruce.robertson5675@tempmail.org,+91-8332208579,Hyderabad,Operations,Beauty,1944-10-05 23:23:09,empty_null_data
709496,9.167959e+08,Robert Taylor,phyllis.kennedy5675@tempmail.org,+91-3525155476,Pune,empty_departmenst,Automotive,empty_null_data,Oracle
709497,4.987294e+09,Jennifer Martinez,ralph.lane5675@tempmail.org,+91-6555421654,Ahmedabad,Research,Toys,1944-10-05 21:23:09,Adobe
709498,4.829243e+08,William Garcia,gloria.warren5675@tempmail.org,+91-1250676049,Bangalore,HR,Food,1944-10-05 20:23:09,Netflix
709499,3.433904e+07,Mary Rodriguez,roy.wells5675@tempmail.org,+91-1573048117,empty_cities,empty_departmenst,Health,1944-10-05 19:23:09,Oracle

In [18]:
d2.isna().sum()

id              70825
name            97086
email               0
phnumber            0
cities              0
departments         0
prdcata             0
datetime            0
companynames        0
dtype: int64

In [14]:
d2[['phnumber','prdcata','datetime','companynames']]=d2[['phnumber','prdcata','datetime','companynames']].fillna("empty_null_data")

In [11]:
d2['cities']=d2['cities'].fillna('empty_cities')

In [10]:
d2['email']=d2['email'].fillna('email_empty')

In [8]:
d2['departments']=d2['departments'].fillna("empty_departmenst")

In [8]:
d2.columns

Index(['id', 'name', 'email', 'phnumber', 'cities', 'departments', 'prdcata',
       'datetime', 'companynames'],
      dtype='object')

In [9]:
d2.shape

(709500, 9)

In [10]:
d2.size

6385500

In [11]:
d2.ndim

2

In [12]:
d2.head(10)

,id,name,email,phnumber,cities,departments,prdcata,datetime,companynames
0,7.087819e+08,John Smith,john.smith@gmail.com,+91-5048609555,Mumbai,Engineering,Electronics,2025-09-13 07:23:04,Apple Inc
1,2.063960e+09,John Smith,john.smith@gmail.com,+91-3236247395,Delhi,Marketing,NaN,2025-09-13 06:23:04,NaN
2,1.538062e+09,Michael Brown,mike.brown@gmail.com,+91-4069018551,Bangalore,NaN,Books,2025-09-13 05:23:04,Apple Inc
3,6.233867e+07,Emily Davis,sarah.johnson@gmail.com,+91-9157527578,Chennai,NaN,Home & Garden,2025-09-13 04:23:04,Amazon
4,1.885852e+07,Emily Davis,sarah.johnson@gmail.com,+91-4718155227,Kolkata,HR,Sports,2025-09-13 03:23:04,Microsoft
5,9.894066e+07,Lisa Anderson,lisa.anderson@yahoo.com,+91-7608728859,Hyderabad,Finance,Beauty,NaN,Tesla
6,6.705763e+07,Robert Taylor,robert.taylor@yahoo.com,+91-8047609091,Mumbai,Sales,Automotive,2025-09-13 01:23:04,Apple Inc
7,4.322607e+07,Emily Davis,jennifer.martinez@yahoo.com,+91-9484872602,NaN,HR,Toys,NaN,NaN
8,5.405867e+09,William Garcia,william.garcia@yahoo.com,+91-3336962716,Jaipur,Research,Food,2025-09-12 23:23:04,Microsoft
9,4.857510e+09,Sarah Johnson,mary.rodriguez@yahoo.com,+91-9819716863,Lucknow,Engineering,NaN,NaN,Oracle

In [14]:
d2.set_index('id')

,name,email,phnumber,cities,departments,prdcata,datetime,companynames
id,,,,,,,,
7.087819e+08,John Smith,john.smith@gmail.com,+91-5048609555,Mumbai,Engineering,Electronics,2025-09-13 07:23:04,Apple Inc
2.063960e+09,John Smith,john.smith@gmail.com,+91-3236247395,Delhi,Marketing,NaN,2025-09-13 06:23:04,NaN
1.538062e+09,Michael Brown,mike.brown@gmail.com,+91-4069018551,Bangalore,NaN,Books,2025-09-13 05:23:04,Apple Inc
6.233867e+07,Emily Davis,sarah.johnson@gmail.com,+91-9157527578,Chennai,NaN,Home & Garden,2025-09-13 04:23:04,Amazon
1.885852e+07,Emily Davis,sarah.johnson@gmail.com,+91-4718155227,Kolkata,HR,Sports,2025-09-13 03:23:04,Microsoft
...,...,...,...,...,...,...,...,...
3.899574e+09,Lisa Anderson,bruce.robertson5675@tempmail.org,+91-8332208579,Hyderabad,Operations,Beauty,1944-10-05 23:23:09,NaN
9.167959e+08,Robert Taylor,phyllis.kennedy5675@tempmail.org,+91-3525155476,Pune,NaN,Automotive,NaN,Oracle
4.987294e+09,Jennifer Martinez,ralph.lane5675@tempmail.org,+91-6555421654,Ahmedabad,Research,Toys,1944-10-05 21:23:09,Adobe
4.829243e+08,William Garcia,gloria.warren5675@tempmail.org,+91-1250676049,Bangalore,HR,Food,1944-10-05 20:23:09,Netflix
3.433904e+07,Mary Rodriguez,roy.wells5675@tempmail.org,+91-1573048117,NaN,NaN,Health,1944-10-05 19:23:09,Oracle

In [16]:
d2.describe()

                 id
count  6.386750e+05
mean   2.031403e+09
std    2.882357e+09
min    1.000020e+07
25%    7.754799e+07
50%    5.497764e+08
75%    3.232111e+09
max    9.999998e+09

In [1]:
d2.info()

NameError: name 'd2' is not defined

In [21]:
d2[['id','prdcata']].value_counts()

id            prdcata
4.369397e+07  Books          2
9.333809e+08  Sports         2
9.348577e+08  Food           2
2.855465e+07  Food           2
2.658710e+07  Beauty         2
                            ..
9.988183e+07  Sports         1
9.988048e+07  Electronics    1
9.988042e+07  Beauty         1
9.987944e+07  Health         1
9.999908e+09  Health         1
Name: count, Length: 575136, dtype: int64

In [22]:
d2.columns

Index(['id', 'name', 'email', 'phnumber', 'cities', 'departments', 'prdcata',
       'datetime', 'companynames'],
      dtype='object')

In [23]:
d3=d2[[ 'name', 'email', 'phnumber', 'cities', 'departments', 'prdcata',
       'datetime', 'companynames']]

In [24]:
d3

,name,email,phnumber,cities,departments,prdcata,datetime,companynames
0,John Smith,john.smith@gmail.com,+91-5048609555,Mumbai,Engineering,Electronics,2025-09-13 07:23:04,Apple Inc
1,John Smith,john.smith@gmail.com,+91-3236247395,Delhi,Marketing,NaN,2025-09-13 06:23:04,NaN
2,Michael Brown,mike.brown@gmail.com,+91-4069018551,Bangalore,NaN,Books,2025-09-13 05:23:04,Apple Inc
3,Emily Davis,sarah.johnson@gmail.com,+91-9157527578,Chennai,NaN,Home & Garden,2025-09-13 04:23:04,Amazon
4,Emily Davis,sarah.johnson@gmail.com,+91-4718155227,Kolkata,HR,Sports,2025-09-13 03:23:04,Microsoft
...,...,...,...,...,...,...,...,...
709495,Lisa Anderson,bruce.robertson5675@tempmail.org,+91-8332208579,Hyderabad,Operations,Beauty,1944-10-05 23:23:09,NaN
709496,Robert Taylor,phyllis.kennedy5675@tempmail.org,+91-3525155476,Pune,NaN,Automotive,NaN,Oracle
709497,Jennifer Martinez,ralph.lane5675@tempmail.org,+91-6555421654,Ahmedabad,Research,Toys,1944-10-05 21:23:09,Adobe
709498,William Garcia,gloria.warren5675@tempmail.org,+91-1250676049,Bangalore,HR,Food,1944-10-05 20:23:09,Netflix
709499,Mary Rodriguez,roy.wells5675@tempmail.org,+91-1573048117,NaN,NaN,Health,1944-10-05 19:23:09,Oracle

In [26]:
d3['name'].value_counts()

name
Michael Brown        61464
Jennifer Martinez    61362
William Garcia       61355
Mary Rodriguez       61234
David Wilson         61222
Emily Davis          61213
Robert Taylor        61206
Lisa Anderson        61155
John Smith           61140
Sarah Johnson        61063
Name: count, dtype: int64

https://www.youtube.com/watch?v=FNLLxYcUnow    
[text](https://www.youtube.com/watch?v=PVVSfqQZ8P0)
https://www.youtube.com/watch?v=SoPrDszsrcw  
https://colab.research.google.com/drive/1D7_9EQuCzhWYqzicr9WEtnCL4NVa3yEU?usp=sharing 
https://colab.research.google.com/drive/1JXpdo3GExMtgMQ3FF6WYXfsxVfTf5GEw?usp=sharing
https://colab.research.google.com/drive/14DHUcOY8oe9vtYZRvvUIA72YajasM5uJ?usp=sharing
https://colab.research.google.com/drive/1_LNCoblRtwJE8RiHIgVW_NzZ9ZBXYdeT?usp=sharing#scrollTo=kKsQG2Ec50lD

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [17]:
x=np.random.rand(10,1).round(1)
y=np.random.rand(10,1).round(2)
x
z=StandardScaler()
normal_df=z.fit_transform(y)
print(normal_df)

[[-0.43576232]
 [ 1.93478471]
 [-0.92381612]
 [ 1.62103584]
 [-0.01743049]
 [ 0.08715246]
 [-1.06326007]
 [-0.81923317]
 [ 0.40090134]
 [-0.78437218]]

In [18]:
x

array([[0.9],
       [0.3],
       [0.7],
       [0.8],
       [0.3],
       [0.9],
       [0.3],
       [1. ],
       [0. ],
       [0.3]])

In [15]:
z=MinMaxScaler()
normal_df=z.fit_transform(x)
print(normal_df)

[[0.        ]
 [0.23404255]
 [1.        ]
 [0.38297872]
 [0.82978723]
 [0.40425532]
 [0.25531915]
 [0.        ]
 [0.12765957]
 [0.36170213]]

In [57]:
data1=np.arange(0,9,1).reshape(3,3)
data2=np.arange(0,9,1).reshape(3,3)

In [48]:
data1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
data2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x_train,x_test,y_train,y_test=train_test_split(data1,data2,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

print(abs(model.score(x_test,y_test)))
print(model.coef_[1])
print(model.intercept_)

nan
[0.33333333 0.33333333 0.33333333]
[-1.0000000e+00  8.8817842e-16  1.0000000e+00]

f:\ExternalSoftwares\Spyder\Vscode\python\packages\Lib\site-packages\sklearn\metrics\_regression.py:1283: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)